#!/usr/bin/env python
# coding: utf-8

# (chap-prerequisites)=
# # Preparation
# 
# This book is entirely written either in the Jupyter Notebook or Markdown. The online version is generated by Jupyter Book.  The first section of this chapter explains how the interactive book works.  In the rest of this chapter, software used in this book and online tools are introduced.
# 
# We will use computer software, *Python*, *JupyterLab*, and *Qiskit*.  In addition, we will use online tools and real quantum computers provided by *IBM Quantum Experience*.  No previous experience is needed.  However, you must train yourself as you read this book.   
# 
# The use of Python, JupyterLab, Qiskit, and IBM Quantum Experience is absolutely required. If you do not have your own computer or the capacity of your computer is limited, free cloud-based online services, such as *IBM Quantum Lab* or *Google Colab* satisfies the requirement. Apart from some inconvenience, they work quite well.  However, it will be convenient to run codes on your computer.  Therefore, it is highly recommended to install required software on your computer.  Installation instruction is given in the following sections.

# In[ ]:




