#!/usr/bin/env python
# coding: utf-8

# (chap-one-qubit-gates)=
# # One-qubit gates

# In quantum computing, we manipulate the state of qubits by applying a series of gates on qubits. In this chapter, I introduce various single-qubit gates commonly used in quantum computing. They are unitary operators in $\mathbb{C}^2$. Some are Hermitian and others are not.  Some are parameter-free and others require parameter values.   {numref}`tbl-q1gates` lists commonly used single-qubit gates.  I explain some the most important ones in the following section.  See also Qiskit documentation

# ```{table} Commonly used single-qubit gates
# :name: tbl-q1gates
# 
# 
# | Generaic Name | Qiskit Class Name |  Qiskit Ciruit Name  | Symbols |
# | :-----------: | :---------------: | :------------------: | :-----: |
# | Pauli X       | XGate             | x                    |  `X`    |
# | Pauli Y       | YGate             | y                    |  `Y`    |
# | Pauli Z       | ZGate             | z                    |  `Z`    |
# | Hadamard      | HGate             | h                    |  `H`    |
# | Sqrt X        | SXGate            | sx                   | `SX`    |
# | Inverse sqrt X | SXdgGate         | sxdg                 | `SX`$^\dagger$ |
# | Sqrt Z        | SGate             | s                    | `S`     |
# | Inverse sqrt Z | SdgGate          | sdg                  |`S`$^\dagger$ |
# | 4th root Z    | TGate             | t                    | `T`     |
# | Inverse 4th root Z | TdgGate      | tdg                  | `T`$^\dagger$ |
# | Phase         | PhaseGate         | p                    | `P`     |
# | Rotation X    | RXGate            | rx                   | `R`$_x$ |
# | Rotation Y    | RYGate            | ry                   | `R`$_y$ |
# | Rotation Z    | RZGate            | rz                   | `R`$_z$ |
# | Unitary 2     | U2Gate            | u2                   | `U`$_2$ |
# | Unitary 3     | UGate             | u                    | `U`|
# ```

# Their definition and typical usage of those gates are explained in the following sections.

# ## Testing quantum circuits using Qiskit
# 
# When we develop a quantum computing algorithm, it will be nice if we can test various idea before executing the code on a real quantum computer.  WE create a quantum circuit and check how the state vector evolve along the circuit.  Note that you cannot do it on a real quantum computer since quantum mechanics odes not allow us to determine the state vector.  However, mathematically we can compute it.  Qiskit provides tools to do so.  `Statevector` function is particularly handy since we can see the state vector in the middle of the quantum circuit.

# **Qiskit example** 
# 
# We construct a simplest quantum circuit which apply a $X$ gate (which we discuss in next page). Then find the state vector generated by the gate.  Again, this is not a simulation of quantum computing. We just want to check if the quantum circuit works as designed by looking at how the state vector changed.  This is only possible in the mathematical world but not in the real quantum world!

# In[1]:


# import QuatumCircuit and QuantumRegister classes.
from qiskit import QuantumCircuit, QuantumRegister   # import QuatumCircuit class
from qiskit.quantum_info import Statevector  # load statevector class

# Preparation
qr=QuantumRegister(1,'q') # create a single qubit with name 'q'.
qc=QuantumCircuit(qr)  # create a quantum circuit

# Intial state
psi0 = Statevector(qc)

#  apply Xgate to 0-th qubit
qc.x(0)

# Final state
psi1 = Statevector(qc)

# Format ket vector with LaTeX.
x = psi0.draw('latex')
y = psi1.draw('latex')

# Show the result using display function
from IPython.display import display, Math
display("Quantum circuit",qc.draw('mpl'),"State vector before the gate",x,"State vector after the gate",y)


# :::{admonition} Python note: Displaying non-text items
# 
# In python, we create many different objects including images.  Usual `print` function can show only texts.   Non-text objects can be shown using `display` function in `Ipaython.display` package.
# 
# In the above example, the image of quantum circuit and LaTeX output are created by `Statevector` class methods and the results are shown with `display` function. 
# 
# :::

# In[ ]:




