#!/usr/bin/env python
# coding: utf-8

# (chap-prerequisites)=
# # Prerequisites
# 
# This book is entirely written in the Jupyter Notebook format and generated by Jupyter Book.  The first section of this chapter explains how the interactive book works.  In the rest of this chapter required software and online tools are introduced.
# 
# We will use computer tools, *Python*, *JupyterLab*, and *Qiskit*.  In addition, we will use online tools and real quantum computers provided by *IBM Quantum Experience*.  No previous experience is needed.  However, you must train yourself along with this book.   
# 
# The use of Python, JupyterLab, Qiskit, and IBM Quantum Experience is required. If you do not have your own computer or the capacity of your computer is limited, free cloud-based online services, such as *IBM Quantum Lab* or *Google Colab* satisfy the requirement. Apart from some inconvenience, they work well.  However, it will be convenient to run codes on your computer.  Therefore, it is highly recommended to install required software on your computer.  Installation instruction is given in the following sections.

# ```{admonition} Downloading the book page
# :class: tip
# :name: download-page
# 
# You can download any page of this book as jupyter notebook (.ipynb).  Move the cursor to the download icon at the upper-right corner and select ".ipynb" with the right mouse button.  Then, select  "save link as ...".  The jupyter notebook file is downloaded to your computer.  You can run it inside your own jupyter lab or upload it to an online service such as IBM Quantum Lab {ref}`sec-IBMQLab`  or {ref}`sec-Colab`.
# 
# You can also download any page as PDF in the same way.  If you prefer to read it on paper, print the PDF file.
# ```

# In[ ]:




